logging:
  level:
    root: WARN
    city.smartb.iris.api: DEBUG

server:
  port: 8889

spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    rest: http://localhost:15672/api

actuator:
  endpoints:
    health:
      sensitive: false