server:
  port: 8083

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-ignored-properties: false
      fail-on-null-creator-properties: false
  webflux:
    base-path: /api

vault:
  scheme: http
  host: localhost
  port: 8200
  token: hvs.UyGDUfBZCvy3Iga6cZqm1okP

ssm:
  signer:
    user:
      name: ssm-admin
      key: user/ssm-admin
    admin:
      name: ssm-admin
      key: user/ssm-admin
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: s2-sample-did
  chaincode:
    url: http://localhost:9090
