include:
  - project: 'framework/fixers/cicd'
    file: 'make/.gitlab-ci.yml'

stages:
  - package

##########################################
## Tasks
##########################################

api:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-iris-vault
