version: "3.3"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./api-driver.yml:/usr/share/nginx/html/doc/api-driver.yml
    environment:
      API_URL: doc/api-driver.yml
