server:
  port: 8085

vault:
  baseUrl: http://localhost:8200

i2:
  issuers:
    -
      name: vault
      authUrl: https://auth.smart-b.io/auth/
      realm: vault-test
      im:
        clientId: vault
