server:
  port: 8084

#spring:
#  jackson:
#    default-property-inclusion: non_null
#    deserialization:
#      fail-on-ignored-properties: false
#      fail-on-null-creator-properties: false
#  webflux:
#    base-path: /1.0

vault:
  scheme: http
  host: localhost
  port: 8200
  token: hvs.UyGDUfBZCvy3Iga6cZqm1okP

ssm:
  couchdb:
    url: http://51.15.215.149:5984
    username: couchdb
    password: couchdb
    serviceName: s2-sample-did
  chaincode:
    url: http://51.15.215.149:9090
  channelId: chaincode
  chaincodeId: sandbox
  ssmName: ssm
